version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/shit-list-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: "/shit-list-ui"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
